"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Zap, Layers, Download, Wand2, ArrowRight, Check } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";

export default function LandingPage() {
  const [loading, setLoading] = useState(false);
  const [showEmailForm, setShowEmailForm] = useState(false);
  const [email, setEmail] = useState("");
  const [sent, setSent] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();
  const supabase = createClient();

  async function handleGetStarted() {
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      router.push("/dashboard");
    } else {
      setShowEmailForm(true);
    }
  }

  async function handleSendMagicLink(e: React.FormEvent) {
    e.preventDefault();
    if (!email) return;
    setLoading(true);
    setError(null);
    const { error } = await supabase.auth.signInWithOtp({
      email,
      options: { emailRedirectTo: `${window.location.origin}/auth/callback?next=/dashboard` },
    });
    if (error) {
      setError(error.message);
    } else {
      setSent(true);
    }
    setLoading(false);
  }

  return (
    <div className="min-h-screen bg-neutral-950 text-white">
      {/* Navbar */}
      <nav className="fixed top-0 inset-x-0 z-50 border-b border-white/5 bg-neutral-950/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-lg bg-brand-600 flex items-center justify-center">
                <Zap className="h-4 w-4 text-white" />
              </div>
              <span className="font-semibold text-lg">InstaCrop</span>
            </div>
            <Button onClick={handleGetStarted} size="sm">
              Get started free
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-4 text-center">
        <div className="max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-sm mb-8">
            <Zap className="h-3.5 w-3.5" />
            AI-powered ad creative engine
          </div>

          <h1 className="text-5xl sm:text-6xl font-bold tracking-tight mb-6 leading-tight">
            One image.{" "}
            <span className="bg-gradient-to-r from-brand-400 to-violet-400 bg-clip-text text-transparent">
              Every ad format.
            </span>
          </h1>

          <p className="text-xl text-neutral-400 max-w-2xl mx-auto mb-10">
            Upload your product photo and get multiple ad creatives in every size —
            Instagram, Facebook, banners, stories — instantly generated by AI.
          </p>

          {!showEmailForm ? (
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Button onClick={handleGetStarted} size="lg">
                Start creating free
                <ArrowRight className="h-4 w-4" />
              </Button>
            </div>
          ) : sent ? (
            <div className="max-w-sm mx-auto text-center p-5 rounded-2xl border border-brand-500/30 bg-brand-500/10">
              <p className="text-brand-300 font-medium">Check your email</p>
              <p className="text-neutral-400 text-sm mt-1">
                We sent a magic link to <strong>{email}</strong>. Click it to sign in.
              </p>
            </div>
          ) : (
            <form onSubmit={handleSendMagicLink} className="max-w-sm mx-auto w-full">
              <div className="flex flex-col sm:flex-row gap-2">
                <input
                  type="email"
                  placeholder="your@email.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  className="flex-1 px-4 py-3 rounded-xl bg-neutral-800 border border-neutral-700 text-white placeholder-neutral-500 focus:outline-none focus:border-brand-500 text-sm"
                />
                <Button type="submit" loading={loading} size="lg">
                  Continue
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </div>
              {error && (
                <p className="mt-2 text-xs text-red-400 text-center">{error}</p>
              )}
            </form>
          )}
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">How it works</h2>
          <p className="text-neutral-400 text-center mb-12 max-w-xl mx-auto">
            Three steps from one product photo to a full set of ad-ready creatives.
          </p>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                step: "1",
                title: "Upload your image",
                description: "Drop in your product photo, ad visual, or source creative. PNG, JPG, or WEBP.",
                icon: <Layers className="h-5 w-5" />,
              },
              {
                step: "2",
                title: "Choose your formats",
                description: "Select the ad sizes and platforms you need. Pick a generation style.",
                icon: <Wand2 className="h-5 w-5" />,
              },
              {
                step: "3",
                title: "Download your creatives",
                description: "AI generates all variants. Preview, compare, and download as a ZIP.",
                icon: <Download className="h-5 w-5" />,
              },
            ].map((item) => (
              <div
                key={item.step}
                className="rounded-2xl border border-white/8 bg-neutral-900/60 p-6"
              >
                <div className="h-10 w-10 rounded-xl bg-brand-600/20 border border-brand-500/30 flex items-center justify-center text-brand-400 mb-4">
                  {item.icon}
                </div>
                <div className="text-xs font-medium text-brand-400 mb-2">Step {item.step}</div>
                <h3 className="text-lg font-semibold mb-2">{item.title}</h3>
                <p className="text-neutral-400 text-sm">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Formats */}
      <section className="py-20 px-4 border-t border-white/5">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">Every format covered</h2>
          <p className="text-neutral-400 text-center mb-12 max-w-xl mx-auto">
            All the sizes you need across every major ad platform.
          </p>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: "Instagram Square", size: "1080×1080" },
              { label: "Instagram Portrait", size: "1080×1350" },
              { label: "Story / Reels", size: "1080×1920" },
              { label: "Facebook Feed", size: "1200×628" },
              { label: "Hero Banner", size: "1920×1080" },
              { label: "Landscape Ad", size: "1600×900" },
              { label: "Wide Banner", size: "1080×566" },
              { label: "Custom", size: "any size" },
            ].map((f) => (
              <div
                key={f.label}
                className="rounded-xl border border-white/8 bg-neutral-900/50 p-3 text-center"
              >
                <p className="text-sm font-medium text-neutral-200">{f.label}</p>
                <p className="text-xs text-neutral-500 mt-0.5">{f.size}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Value props */}
      <section className="py-20 px-4 border-t border-white/5">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">
            Built for businesses that move fast
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            {[
              "Generate multiple creative variants for A/B testing",
              "AI matches backgrounds to your product automatically",
              "Smart recomposition for every aspect ratio",
              "Product isolation for cleaner scene placement",
              "Download everything as a ZIP in one click",
              "Save generation history for every job",
            ].map((item) => (
              <div key={item} className="flex items-start gap-3 p-4 rounded-xl bg-neutral-900/50 border border-white/5">
                <div className="h-5 w-5 rounded-full bg-brand-500/20 border border-brand-500/30 flex items-center justify-center shrink-0 mt-0.5">
                  <Check className="h-3 w-3 text-brand-400" />
                </div>
                <span className="text-sm text-neutral-300">{item}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-4 border-t border-white/5">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-4xl font-bold mb-4">Ready to create?</h2>
          <p className="text-neutral-400 mb-8">
            Start generating professional ad creatives from a single product photo.
          </p>
          <Button onClick={handleGetStarted} size="lg">
            Get started free
            <ArrowRight className="h-4 w-4" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8 px-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-6 w-6 rounded-md bg-brand-600 flex items-center justify-center">
              <Zap className="h-3 w-3 text-white" />
            </div>
            <span className="text-sm text-neutral-400">InstaCrop</span>
          </div>
          <p className="text-xs text-neutral-600">AI-powered ad creative engine</p>
        </div>
      </footer>
    </div>
  );
}
